name: myweatherapp
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  geolocator: ^5.3.2+2
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
